export const GET_HASHTAGS = 'GET_HASHTAGS';
export const GET_HASHTAGS_SECCESS = 'GET_HASHTAGS_SECCESS';
export const GET_HASHTAGS_ERROR = 'GET_HASHTAGS_ERROR';
export const DISMISS_ERROR = 'DISMISS_ERROR';